spring.datasource.url=jdbc:postgresql://dpg-d8h5mq37uimc73cjf9s0-a.singapore-postgres.render.com:5432/campus_complaint?sslmode=require
spring.datasource.username=campus_complaint_user
spring.datasource.password=sqzSApDq9l7jeZAGkEfV9Ac1YzCY7nPT
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=mySecretKeyForCampusComplaintManagementSystem123456

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

cloudinary.cloud-name=dcckljxjl
cloudinary.api-key=542781289687356
cloudinary.api-secret=_bTUYPMVviXaKTYM3aIW9fFzl2k

server.port=8080