spring.application.name=campus-complaint-system

spring.datasource.url=spring.datasource.url=jdbc:postgresql://ep-square-field-ao1qf7ci.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channelBinding=require

spring.datasource.username= neondb_owner

spring.datasource.password=npg_ZgkA73npVjKM

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
jwt.secret=mySecretKeyForCampusComplaintManagementSystem123456

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

cloudinary.cloud-name=dcckljxjl
cloudinary.api-key=542781289687356
cloudinary.api-secret=_bTUYPMVviXaKTYM3aIW9fFzl2k

server.port=8080