package com.campuscomplaint.service;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.mail.SimpleMailMessage;
import org.springframework.mail.javamail.JavaMailSender;
import org.springframework.stereotype.Service;

@Service
@RequiredArgsConstructor
@Slf4j
public class EmailService {

    private final JavaMailSender mailSender;

    public void sendNotificationEmail(String toEmail, String subject, String message) {
        try {
            SimpleMailMessage email = new SimpleMailMessage();
            email.setTo(toEmail);
            email.setSubject(subject);
            email.setText(message);
            email.setFrom("noreply@campuscomplaint.com"); // replace with your sender email

            mailSender.send(email);
            log.info("Email sent to: {}", toEmail);
        } catch (Exception e) {
            log.error("Failed to send email to {}: {}", toEmail, e.getMessage());
            // Don't throw — if email fails, notification is still saved in DB
        }
    }

    // fixed parameter name (no space)
    public void sendComplaintNotification(String facultyEmail, String complaintTitle, Long complaintId) {

        String subject = "[Campus Complaint System] New Complaint Received";

        String body = """
            Dear Faculty Member,

            You have received a new complaint that has been assigned for review.

            ==================================================
            COMPLAINT INFORMATION
            ==================================================
            Complaint ID : #%d
            Title        : %s
            ==================================================

            Action Required:
            • Review the complaint details.
            • Investigate the reported issue.
            • Update the complaint status accordingly.

            Please access the Campus Complaint Management System at your earliest convenience.

            Thank you for your cooperation in maintaining a responsive and efficient grievance redressal process.

            --------------------------------------------------
            This is an automated email generated by the
            Campus Complaint Management System.
            Please do not reply to this message.
            --------------------------------------------------

            Regards,
            Campus Complaint Management System
            """.formatted(complaintId, complaintTitle);

        sendNotificationEmail(facultyEmail, subject, body);
    }

    public void sendFeedbackRequestEmail(String studentEmail, Long complaintId) {
        String subject = "Feedback Requested for Complaint #" + complaintId;
        String body = "Your complaint #" + complaintId + " has been resolved.\n\n"
                + "Please provide your feedback to help us improve.";
        sendNotificationEmail(studentEmail, subject, body);
    }

    public void sendFeedbackSubmittedEmail(String facultyEmail, Long complaintId) {
        String subject = "Feedback Submitted for Complaint #" + complaintId;
        String body = "Student feedback has been submitted for complaint #" + complaintId + ".";
        sendNotificationEmail(facultyEmail, subject, body);
    }
}