package com.campuscomplaint.service;

import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Service;
import org.springframework.web.client.RestTemplate;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

@Service
@Slf4j
public class EmailService {

    private final RestTemplate restTemplate;

    @Value("${BREVO_API_KEY:}")
    private String apiKey;

    @Value("${brevo.sender.email}")
    private String senderEmail;

    @Value("${brevo.sender.name}")
    private String senderName;

    public EmailService() {
        this.restTemplate = new RestTemplate();
    }

    public void sendNotificationEmail(String toEmail, String subject, String message) {
        if (apiKey == null || apiKey.trim().isEmpty()) {
            log.warn("Brevo API key is not configured. Email to {} was not sent. Content: {}", toEmail, message);
            return;
        }

        try {
            HttpHeaders headers = new HttpHeaders();
            headers.setContentType(MediaType.APPLICATION_JSON);
            headers.set("api-key", apiKey);
            headers.set("accept", "application/json");

            Map<String, Object> body = new HashMap<>();
            body.put("sender", Map.of("email", senderEmail, "name", senderName));
            body.put("to", List.of(Map.of("email", toEmail)));
            body.put("subject", subject);
            body.put("textContent", message);

            HttpEntity<Map<String, Object>> entity = new HttpEntity<>(body, headers);

            ResponseEntity<String> response = restTemplate.postForEntity(
                    "https://api.brevo.com/v3/smtp/email",
                    entity,
                    String.class
            );

            if (response.getStatusCode().is2xxSuccessful()) {
                log.info("Email sent successfully to {} via Brevo API.", toEmail);
            } else {
                log.error("Failed to send email to {} via Brevo. Status: {}, Response: {}", 
                        toEmail, response.getStatusCode(), response.getBody());
            }
        } catch (Exception e) {
            log.error("Failed to send email to {} via Brevo API: {}", toEmail, e.getMessage());
            // Don't throw — if email fails, notification is still saved in DB
        }
    }

    // fixed parameter name (no space)
    public void sendComplaintNotification(String facultyEmail, String complaintTitle, Long complaintId) {

        String subject = "[Campus Complaint System] New Complaint Received";

        String body = """
            Dear Faculty Member,

            You have received a new complaint that has been assigned for review.

            ==================================================
            COMPLAINT INFORMATION
            ==================================================
            Complaint ID : #%d
            Title        : %s
            ==================================================

            Action Required:
            • Review the complaint details.
            • Investigate the reported issue.
            • Update the complaint status accordingly.

            Please access the Campus Complaint Management System at your earliest convenience.

            Thank you for your cooperation in maintaining a responsive and efficient grievance redressal process.

            --------------------------------------------------
            This is an automated email generated by the
            Campus Complaint Management System.
            Please do not reply to this message.
            --------------------------------------------------

            Regards,
            Campus Complaint Management System
            """.formatted(complaintId, complaintTitle);

        sendNotificationEmail(facultyEmail, subject, body);
    }

    public void sendStudentComplaintRegisteredNotification(String studentEmail, String complaintTitle, Long complaintId) {
        String subject = "[Campus Complaint System] Complaint Successfully Registered";

        String body = """
            Dear Student,

            Your complaint has been successfully registered in the Campus Complaint Management System.

            ==================================================
            COMPLAINT INFORMATION
            ==================================================
            Complaint ID : #%d
            Title        : %s
            ==================================================

            Next Steps:
            • A faculty member will review your complaint shortly.
            • You will receive email notifications as the status of your complaint updates.
            
            You can track the live progress of your ticket directly from your student dashboard.

            Thank you for helping us maintain a better campus environment.

            --------------------------------------------------
            This is an automated email generated by the
            Campus Complaint Management System.
            Please do not reply to this message.
            --------------------------------------------------

            Regards,
            Campus Complaint Management System
            """.formatted(complaintId, complaintTitle);

        sendNotificationEmail(studentEmail, subject, body);
    }

    public void sendStudentFeedbackRequestNotification(String studentEmail, String complaintTitle, Long complaintId) {
        String subject = "[Campus Complaint System] Complaint Resolved - Feedback Requested";

        String body = """
            Dear Student,

            Your complaint has been resolved by our faculty review team.

            ==================================================
            RESOLVED COMPLAINT INFORMATION
            ==================================================
            Complaint ID : #%d
            Title        : %s
            ==================================================

            Action Required:
            • Please log in to the system.
            • Review the resolution remarks.
            • Provide your feedback/rating to help us evaluate and improve our services.

            We appreciate your patience throughout this process.

            --------------------------------------------------
            This is an automated email generated by the
            Campus Complaint Management System.
            Please do not reply to this message.
            --------------------------------------------------

            Regards,
            Campus Complaint Management System
            """.formatted(complaintId, complaintTitle);

        sendNotificationEmail(studentEmail, subject, body);
    }

    public void sendFeedbackRequestEmail(String studentEmail, Long complaintId) {
        String subject = "Feedback Requested for Complaint #" + complaintId;
        String body = "Your complaint #" + complaintId + " has been resolved.\n\n"
                + "Please provide your feedback to help us improve.";
        sendNotificationEmail(studentEmail, subject, body);
    }

    public void sendFeedbackSubmittedEmail(String facultyEmail, Long complaintId) {
        String subject = "Feedback Submitted for Complaint #" + complaintId;
        String body = "Student feedback has been submitted for complaint #" + complaintId + ".";
        sendNotificationEmail(facultyEmail, subject, body);
    }
}